package drain

import (
	"context"
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/x7ssss/dbdrain/internal/anonymize"
	"github.com/x7ssss/dbdrain/internal/graph"
	"github.com/x7ssss/dbdrain/internal/introspect"
)

// Config holds export configuration.
type Config struct {
	Schema          string
	AnonymizePII    bool
	Salt            string
	MaxRowsPerTable int // 0 = unlimited
	MaxDepth        int // 0 = unlimited (downward traversal only)
}

// Row is a single fetched database row: column values in schema order.
type Row struct {
	Table  string
	ColNames []string
	Cols   []introspect.Column
	Vals   []interface{}
}

// Exporter streams SQL INSERT statements to a writer.
type Exporter struct {
	conn    *pgx.Conn
	schema  *introspect.Schema
	g       *graph.Graph
	sccs    []graph.SCC
	cfg     Config
	masker  *anonymize.Masker
	visited map[string]map[string]bool // table -> set of row PKs

	// RowCounts tracks how many rows were emitted per table (for summary).
	RowCounts map[string]int
}

// New creates a new Exporter.
func New(conn *pgx.Conn, schema *introspect.Schema, g *graph.Graph, sccs []graph.SCC, cfg Config) *Exporter {
	var masker *anonymize.Masker
	if cfg.AnonymizePII {
		masker = anonymize.New(cfg.Salt)
	}
	return &Exporter{
		conn:      conn,
		schema:    schema,
		g:         g,
		sccs:      sccs,
		cfg:       cfg,
		masker:    masker,
		visited:   make(map[string]map[string]bool),
		RowCounts: make(map[string]int),
	}
}

// hasCycles returns true if any SCC has a cycle.
func (e *Exporter) hasCycles() bool {
	for _, scc := range e.sccs {
		if scc.HasCycle {
			return true
		}
	}
	return false
}

// Export writes the full SQL dump to w, starting from the anchor table/query.
func (e *Exporter) Export(ctx context.Context, w io.Writer, anchorTable string, anchorWhere string, anchorLimit int) error {
	// Write SQL header
	fmt.Fprintf(w, "-- Generated by dbdrain v0.2.0 on %s\n", time.Now().UTC().Format(time.RFC3339))
	fmt.Fprintf(w, "-- Anchor: %s WHERE %s LIMIT %d\n\n", anchorTable, anchorWhere, anchorLimit)
	fmt.Fprintln(w, "BEGIN;")
	if e.hasCycles() {
		fmt.Fprintln(w, "SET CONSTRAINTS ALL DEFERRED;")
	}
	fmt.Fprintln(w, "")

	// Run inside a REPEATABLE READ snapshot transaction for consistency.
	tx, err := e.conn.BeginTx(ctx, pgx.TxOptions{IsoLevel: pgx.RepeatableRead, AccessMode: pgx.ReadOnly})
	if err != nil {
		return fmt.Errorf("begin tx: %w", err)
	}
	defer tx.Rollback(ctx)

	// Resolve self-referencing hierarchy on the anchor table (if self-FK exists).
	if err := e.resolveSelfRef(ctx, tx, w, anchorTable, anchorWhere, anchorLimit); err != nil {
		return fmt.Errorf("resolve self-ref hierarchy: %w", err)
	}

	// Fetch anchor rows (skips rows already visited by self-ref resolution).
	if _, err := e.fetchAndEmit(ctx, tx, w, anchorTable, anchorWhere, anchorLimit); err != nil {
		return fmt.Errorf("fetch anchor: %w", err)
	}

	// BFS upward traversal: pull ALL ancestor rows required by FK constraints (mandatory).
	if err := e.bfsParents(ctx, tx, w, anchorTable); err != nil {
		return fmt.Errorf("traverse parents: %w", err)
	}

	// BFS downward traversal: pull direct children up to --depth levels.
	if err := e.bfsChildren(ctx, tx, w, anchorTable, 0); err != nil {
		return fmt.Errorf("traverse children: %w", err)
	}

	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "COMMIT;")
	return nil
}

// ExportToTarget executes inserts directly against a target pgx.Conn instead of emitting SQL text.
func (e *Exporter) ExportToTarget(ctx context.Context, targetConn *pgx.Conn, anchorTable string, anchorWhere string, anchorLimit int, progressFn func(table string, n int)) error {
	// Read-only snapshot on source.
	tx, err := e.conn.BeginTx(ctx, pgx.TxOptions{IsoLevel: pgx.RepeatableRead, AccessMode: pgx.ReadOnly})
	if err != nil {
		return fmt.Errorf("begin source tx: %w", err)
	}
	defer tx.Rollback(ctx)

	// Collect all rows first into an ordered slice.
	var rows []Row

	// Self-ref resolution into rows slice.
	if err := e.resolveSelfRefRows(ctx, tx, anchorTable, anchorWhere, anchorLimit, &rows); err != nil {
		return fmt.Errorf("self-ref resolution: %w", err)
	}

	// Anchor rows.
	if err := e.collectRows(ctx, tx, anchorTable, anchorWhere, anchorLimit, &rows); err != nil {
		return fmt.Errorf("collect anchor rows: %w", err)
	}

	// Parents.
	if err := e.collectParents(ctx, tx, anchorTable, &rows); err != nil {
		return fmt.Errorf("collect parents: %w", err)
	}

	// Children.
	if err := e.collectChildren(ctx, tx, anchorTable, 0, &rows); err != nil {
		return fmt.Errorf("collect children: %w", err)
	}

	// Write to target inside a single transaction.
	targetTx, err := targetConn.Begin(ctx)
	if err != nil {
		return fmt.Errorf("begin target tx: %w", err)
	}
	defer targetTx.Rollback(ctx)

	if _, err := targetTx.Exec(ctx, "SET CONSTRAINTS ALL DEFERRED;"); err != nil {
		return fmt.Errorf("set deferred: %w", err)
	}

	for _, row := range rows {
		if err := e.insertRow(ctx, targetTx, row); err != nil {
			return fmt.Errorf("insert row into %s: %w", row.Table, err)
		}
		if progressFn != nil {
			progressFn(row.Table, 1)
		}
	}

	if err := targetTx.Commit(ctx); err != nil {
		return fmt.Errorf("commit target: %w", err)
	}

	return nil
}

// insertRow executes a single INSERT ON CONFLICT DO NOTHING on targetTx.
func (e *Exporter) insertRow(ctx context.Context, tx pgx.Tx, row Row) error {
	quoted := make([]string, len(row.ColNames))
	placeholders := make([]string, len(row.ColNames))
	for i, c := range row.ColNames {
		quoted[i] = quoteIdent(c)
		placeholders[i] = fmt.Sprintf("$%d", i+1)
	}
	query := fmt.Sprintf(
		"INSERT INTO %s.%s (%s) VALUES (%s) ON CONFLICT DO NOTHING",
		quoteIdent(e.cfg.Schema),
		quoteIdent(row.Table),
		strings.Join(quoted, ", "),
		strings.Join(placeholders, ", "),
	)
	_, err := tx.Exec(ctx, query, row.Vals...)
	return err
}

// -------------------------------------------------------------------------
// Self-referencing hierarchy resolution
// -------------------------------------------------------------------------

// isSelfRef returns true if the table has a foreign key referencing itself.
func (e *Exporter) isSelfRef(table string) bool {
	for _, edge := range e.g.OutEdges[table] {
		if edge.ToTable == table {
			return true
		}
	}
	return false
}

// selfRefEdge returns the first self-referencing edge for a table, or nil.
func (e *Exporter) selfRefEdge(table string) *graph.Edge {
	for i, edge := range e.g.OutEdges[table] {
		if edge.ToTable == table {
			return &e.g.OutEdges[table][i]
		}
	}
	return nil
}

// resolveSelfRef emits SQL for the full self-referencing hierarchy using a
// recursive CTE. Both upward (ancestors) and downward (direct children) paths
// are resolved to keep the hierarchy intact.
func (e *Exporter) resolveSelfRef(ctx context.Context, tx pgx.Tx, w io.Writer, table string, anchorWhere string, limit int) error {
	edge := e.selfRefEdge(table)
	if edge == nil {
		return nil
	}
	if len(edge.FromColumns) != 1 || len(edge.ToColumns) != 1 {
		return nil // composite self-ref not supported
	}

	childCol := edge.FromColumns[0]  // e.g. parent_id
	parentCol := edge.ToColumns[0]   // e.g. id

	cols := e.schema.Columns[table]
	if len(cols) == 0 {
		return nil
	}
	colNames := make([]string, len(cols))
	for i, c := range cols {
		colNames[i] = c.Name
	}

	schemaQ := quoteIdent(e.cfg.Schema)
	tableQ := quoteIdent(table)
	childColQ := quoteIdent(childCol)
	parentColQ := quoteIdent(parentCol)
	selectCols := "t." + strings.Join(colNames, ", t.")

	// Build seed WHERE clause.
	seedWhere := ""
	if anchorWhere != "" {
		seedWhere = "WHERE " + anchorWhere
	}
	seedLimit := ""
	if limit > 0 {
		seedLimit = fmt.Sprintf("LIMIT %d", limit)
	}

	// Recursive CTE: walk both upward (ancestors) and downward (children) from seeds.
	cteSQL := fmt.Sprintf(`
WITH RECURSIVE hierarchy AS (
  -- seed: anchor rows
  SELECT %s FROM %s.%s t %s %s
  UNION
  -- ancestors: walk up the parent chain
  SELECT %s FROM %s.%s t
  INNER JOIN hierarchy h ON t.%s = h.%s
  UNION
  -- descendants: walk down the child chain
  SELECT %s FROM %s.%s t
  INNER JOIN hierarchy h ON t.%s = h.%s
)
SELECT DISTINCT * FROM hierarchy`,
		selectCols, schemaQ, tableQ, seedWhere, seedLimit,
		selectCols, schemaQ, tableQ, parentColQ, childColQ,
		selectCols, schemaQ, tableQ, childColQ, parentColQ,
	)

	rows, err := tx.Query(ctx, cteSQL)
	if err != nil {
		return fmt.Errorf("recursive CTE for %s: %w", table, err)
	}
	defer rows.Close()

	pkCols := e.schema.PrimaryKeys[table]
	for rows.Next() {
		vals, err := rows.Values()
		if err != nil {
			return fmt.Errorf("row values: %w", err)
		}
		pk := buildPK(pkCols, colNames, vals)
		if e.markVisited(table, pk) {
			continue
		}
		if e.masker != nil {
			applyMasking(e.masker, cols, vals)
		}
		fmt.Fprintf(w, "INSERT INTO %s.%s (%s) VALUES (%s) ON CONFLICT DO NOTHING;\n",
			schemaQ, tableQ,
			strings.Join(quotedColNames(colNames), ", "),
			formatValues(cols, vals),
		)
		e.RowCounts[table]++
	}
	return rows.Err()
}

// resolveSelfRefRows collects hierarchy rows into a slice (for target streaming).
func (e *Exporter) resolveSelfRefRows(ctx context.Context, tx pgx.Tx, table string, anchorWhere string, limit int, out *[]Row) error {
	edge := e.selfRefEdge(table)
	if edge == nil {
		return nil
	}
	if len(edge.FromColumns) != 1 || len(edge.ToColumns) != 1 {
		return nil
	}

	childCol := edge.FromColumns[0]
	parentCol := edge.ToColumns[0]

	cols := e.schema.Columns[table]
	if len(cols) == 0 {
		return nil
	}
	colNames := make([]string, len(cols))
	for i, c := range cols {
		colNames[i] = c.Name
	}

	schemaQ := quoteIdent(e.cfg.Schema)
	tableQ := quoteIdent(table)
	selectCols := "t." + strings.Join(colNames, ", t.")
	seedWhere := ""
	if anchorWhere != "" {
		seedWhere = "WHERE " + anchorWhere
	}
	seedLimit := ""
	if limit > 0 {
		seedLimit = fmt.Sprintf("LIMIT %d", limit)
	}

	cteSQL := fmt.Sprintf(`
WITH RECURSIVE hierarchy AS (
  SELECT %s FROM %s.%s t %s %s
  UNION
  SELECT %s FROM %s.%s t INNER JOIN hierarchy h ON t.%s = h.%s
  UNION
  SELECT %s FROM %s.%s t INNER JOIN hierarchy h ON t.%s = h.%s
)
SELECT DISTINCT * FROM hierarchy`,
		selectCols, schemaQ, tableQ, seedWhere, seedLimit,
		selectCols, schemaQ, tableQ, quoteIdent(parentCol), quoteIdent(childCol),
		selectCols, schemaQ, tableQ, quoteIdent(childCol), quoteIdent(parentCol),
	)

	rows, err := tx.Query(ctx, cteSQL)
	if err != nil {
		return fmt.Errorf("recursive CTE for %s: %w", table, err)
	}
	defer rows.Close()

	pkCols := e.schema.PrimaryKeys[table]
	for rows.Next() {
		vals, err := rows.Values()
		if err != nil {
			return err
		}
		pk := buildPK(pkCols, colNames, vals)
		if e.markVisited(table, pk) {
			continue
		}
		if e.masker != nil {
			applyMasking(e.masker, cols, vals)
		}
		*out = append(*out, Row{Table: table, ColNames: colNames, Cols: cols, Vals: vals})
		e.RowCounts[table]++
	}
	return rows.Err()
}

// -------------------------------------------------------------------------
// BFS traversal (SQL emission path)
// -------------------------------------------------------------------------

// bfsParents performs upward BFS traversal, pulling all ancestor rows.
// Upward traversal is unbounded (mandatory for referential integrity).
func (e *Exporter) bfsParents(ctx context.Context, tx pgx.Tx, w io.Writer, startTable string) error {
	queue := []string{startTable}
	enqueuedParents := map[string]bool{startTable: true}

	for len(queue) > 0 {
		table := queue[0]
		queue = queue[1:]

		for _, edge := range e.g.OutEdges[table] {
			parent := edge.ToTable
			if parent == table {
				continue // self-ref handled separately
			}
			if len(edge.ToColumns) != 1 {
				continue // composite FK: skip for now
			}

			// Collect FK column values from visited rows of `table`.
			fkVals := e.collectFKValues(table, edge.FromColumns[0], edge.ToColumns[0])
			if len(fkVals) == 0 {
				continue
			}

			whereClause := fmt.Sprintf("%s IN (%s)", quoteIdent(edge.ToColumns[0]), formatStringList(fkVals))
			if _, err := e.fetchAndEmit(ctx, tx, w, parent, whereClause, 0); err != nil {
				return err
			}

			if !enqueuedParents[parent] {
				enqueuedParents[parent] = true
				queue = append(queue, parent)
			}
		}
	}
	return nil
}

// bfsChildren performs downward BFS traversal up to cfg.MaxDepth levels.
func (e *Exporter) bfsChildren(ctx context.Context, tx pgx.Tx, w io.Writer, startTable string, depth int) error {
	type work struct {
		table string
		depth int
	}
	queue := []work{{startTable, 0}}
	enqueuedChildren := map[string]bool{startTable: true}

	for len(queue) > 0 {
		item := queue[0]
		queue = queue[1:]

		if e.cfg.MaxDepth > 0 && item.depth >= e.cfg.MaxDepth {
			continue
		}

		for _, edge := range e.g.InEdges[item.table] {
			child := edge.FromTable
			if child == item.table {
				continue // self-ref handled separately
			}
			if len(edge.FromColumns) != 1 {
				continue
			}

			fkVals := e.collectFKValues(item.table, edge.ToColumns[0], edge.FromColumns[0])
			if len(fkVals) == 0 {
				continue
			}

			cap := e.cfg.MaxRowsPerTable
			whereClause := fmt.Sprintf("%s IN (%s)", quoteIdent(edge.FromColumns[0]), formatStringList(fkVals))
			if _, err := e.fetchAndEmit(ctx, tx, w, child, whereClause, cap); err != nil {
				return err
			}

			if !enqueuedChildren[child] {
				enqueuedChildren[child] = true
				queue = append(queue, work{child, item.depth + 1})
			}
		}
	}
	return nil
}

// -------------------------------------------------------------------------
// BFS traversal (target streaming path — collects rows)
// -------------------------------------------------------------------------

func (e *Exporter) collectParents(ctx context.Context, tx pgx.Tx, startTable string, out *[]Row) error {
	queue := []string{startTable}
	enqueuedParents := map[string]bool{startTable: true}

	for len(queue) > 0 {
		table := queue[0]
		queue = queue[1:]

		for _, edge := range e.g.OutEdges[table] {
			parent := edge.ToTable
			if parent == table || len(edge.ToColumns) != 1 {
				continue
			}
			fkVals := e.collectFKValues(table, edge.FromColumns[0], edge.ToColumns[0])
			if len(fkVals) == 0 {
				continue
			}
			whereClause := fmt.Sprintf("%s IN (%s)", quoteIdent(edge.ToColumns[0]), formatStringList(fkVals))
			if err := e.collectRows(ctx, tx, parent, whereClause, 0, out); err != nil {
				return err
			}
			if !enqueuedParents[parent] {
				enqueuedParents[parent] = true
				queue = append(queue, parent)
			}
		}
	}
	return nil
}

func (e *Exporter) collectChildren(ctx context.Context, tx pgx.Tx, startTable string, depth int, out *[]Row) error {
	type work struct {
		table string
		depth int
	}
	queue := []work{{startTable, 0}}
	enqueuedChildren := map[string]bool{startTable: true}

	for len(queue) > 0 {
		item := queue[0]
		queue = queue[1:]

		if e.cfg.MaxDepth > 0 && item.depth >= e.cfg.MaxDepth {
			continue
		}

		for _, edge := range e.g.InEdges[item.table] {
			child := edge.FromTable
			if child == item.table || len(edge.FromColumns) != 1 {
				continue
			}
			fkVals := e.collectFKValues(item.table, edge.ToColumns[0], edge.FromColumns[0])
			if len(fkVals) == 0 {
				continue
			}
			cap := e.cfg.MaxRowsPerTable
			whereClause := fmt.Sprintf("%s IN (%s)", quoteIdent(edge.FromColumns[0]), formatStringList(fkVals))
			if err := e.collectRows(ctx, tx, child, whereClause, cap, out); err != nil {
				return err
			}
			if !enqueuedChildren[child] {
				enqueuedChildren[child] = true
				queue = append(queue, work{child, item.depth + 1})
			}
		}
	}
	return nil
}

// -------------------------------------------------------------------------
// Core fetch helpers
// -------------------------------------------------------------------------

// markVisited marks a row as visited. Returns true if already visited.
func (e *Exporter) markVisited(table string, pk string) bool {
	if _, ok := e.visited[table]; !ok {
		e.visited[table] = make(map[string]bool)
	}
	if e.visited[table][pk] {
		return true
	}
	e.visited[table][pk] = true
	return false
}

// collectFKValues returns the string values of a given column across all visited rows of a table.
// parentCol is the column being looked up in the referenced table (used for WHERE clause construction).
// srcCol is the column in the source table that holds the FK value.
func (e *Exporter) collectFKValues(table, srcCol, _ string) []string {
	// We can't recover per-column values from the visited PK map directly for composite PKs,
	// so we return the visited PK set (valid when the PK is a single column, which is the FK target).
	// For composite FKs this is a no-op (handled upstream with len check).
	_ = srcCol
	var vals []string
	for pk := range e.visited[table] {
		vals = append(vals, pk)
	}
	return vals
}

// fetchAndEmit fetches rows and emits INSERT statements. Returns new PKs added.
func (e *Exporter) fetchAndEmit(ctx context.Context, tx pgx.Tx, w io.Writer, table string, whereClause string, limit int) ([]string, error) {
	cols := e.schema.Columns[table]
	if len(cols) == 0 {
		return nil, nil
	}
	colNames := make([]string, len(cols))
	for i, c := range cols {
		colNames[i] = c.Name
	}

	query := buildQuery(e.cfg.Schema, table, colNames, whereClause, limit)

	rows, err := tx.Query(ctx, query)
	if err != nil {
		return nil, fmt.Errorf("query %s: %w", table, err)
	}
	defer rows.Close()

	pkCols := e.schema.PrimaryKeys[table]
	var pks []string

	for rows.Next() {
		vals, err := rows.Values()
		if err != nil {
			return nil, fmt.Errorf("row values %s: %w", table, err)
		}

		pk := buildPK(pkCols, colNames, vals)
		if e.markVisited(table, pk) {
			continue
		}
		pks = append(pks, pk)

		if e.masker != nil {
			applyMasking(e.masker, cols, vals)
		}

		fmt.Fprintf(w, "INSERT INTO %s.%s (%s) VALUES (%s) ON CONFLICT DO NOTHING;\n",
			quoteIdent(e.cfg.Schema),
			quoteIdent(table),
			strings.Join(quotedColNames(colNames), ", "),
			formatValues(cols, vals),
		)
		e.RowCounts[table]++
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("rows err %s: %w", table, err)
	}

	return pks, nil
}

// collectRows fetches rows into a []Row slice (for target streaming).
func (e *Exporter) collectRows(ctx context.Context, tx pgx.Tx, table string, whereClause string, limit int, out *[]Row) error {
	cols := e.schema.Columns[table]
	if len(cols) == 0 {
		return nil
	}
	colNames := make([]string, len(cols))
	for i, c := range cols {
		colNames[i] = c.Name
	}

	query := buildQuery(e.cfg.Schema, table, colNames, whereClause, limit)
	rows, err := tx.Query(ctx, query)
	if err != nil {
		return fmt.Errorf("query %s: %w", table, err)
	}
	defer rows.Close()

	pkCols := e.schema.PrimaryKeys[table]
	for rows.Next() {
		vals, err := rows.Values()
		if err != nil {
			return fmt.Errorf("row values %s: %w", table, err)
		}
		pk := buildPK(pkCols, colNames, vals)
		if e.markVisited(table, pk) {
			continue
		}
		if e.masker != nil {
			applyMasking(e.masker, cols, vals)
		}
		*out = append(*out, Row{Table: table, ColNames: colNames, Cols: cols, Vals: vals})
		e.RowCounts[table]++
	}
	return rows.Err()
}

// -------------------------------------------------------------------------
// Helper utilities
// -------------------------------------------------------------------------

func applyMasking(m *anonymize.Masker, cols []introspect.Column, vals []interface{}) {
	for i, col := range cols {
		if vals[i] != nil {
			strVal := fmt.Sprintf("%v", vals[i])
			masked := m.MaskColumn(col.Name, strVal)
			if masked != strVal {
				vals[i] = masked
			}
		}
	}
}

func buildQuery(schema, table string, colNames []string, whereClause string, limit int) string {
	q := fmt.Sprintf(`SELECT %s FROM %s.%s`,
		quoteIdents(colNames),
		quoteIdent(schema),
		quoteIdent(table),
	)
	if whereClause != "" {
		q += " WHERE " + whereClause
	}
	if limit > 0 {
		q += fmt.Sprintf(" LIMIT %d", limit)
	}
	return q
}

func quoteIdent(s string) string {
	return `"` + strings.ReplaceAll(s, `"`, `""`) + `"`
}

func quoteIdents(ss []string) string {
	parts := make([]string, len(ss))
	for i, s := range ss {
		parts[i] = quoteIdent(s)
	}
	return strings.Join(parts, ", ")
}

func quotedColNames(names []string) []string {
	out := make([]string, len(names))
	for i, n := range names {
		out[i] = quoteIdent(n)
	}
	return out
}

func buildPK(pkCols []string, colNames []string, vals []interface{}) string {
	if len(pkCols) == 0 {
		return fmt.Sprintf("%v", vals)
	}
	parts := make([]string, 0, len(pkCols))
	for _, pk := range pkCols {
		for j, col := range colNames {
			if col == pk {
				parts = append(parts, fmt.Sprintf("%v", vals[j]))
				break
			}
		}
	}
	return strings.Join(parts, ",")
}

func formatValues(cols []introspect.Column, vals []interface{}) string {
	parts := make([]string, len(vals))
	for i, v := range vals {
		parts[i] = formatValue(cols[i], v)
	}
	return strings.Join(parts, ", ")
}

func formatValue(col introspect.Column, v interface{}) string {
	if v == nil {
		return "NULL"
	}
	switch val := v.(type) {
	case bool:
		if val {
			return "TRUE"
		}
		return "FALSE"
	case int, int8, int16, int32, int64,
		uint, uint8, uint16, uint32, uint64,
		float32, float64:
		return fmt.Sprintf("%v", val)
	case []byte:
		dt := strings.ToLower(col.DataType)
		if strings.Contains(dt, "json") {
			return "'" + escapeSQLString(string(val)) + "'"
		}
		return fmt.Sprintf("'\\x%s'", fmt.Sprintf("%x", val))
	case time.Time:
		return fmt.Sprintf("'%s'", val.UTC().Format(time.RFC3339Nano))
	case [16]byte:
		return fmt.Sprintf("'%s'", formatUUID(val))
	default:
		return "'" + escapeSQLString(fmt.Sprintf("%v", val)) + "'"
	}
}

func escapeSQLString(s string) string {
	return strings.ReplaceAll(s, "'", "''")
}

func formatUUID(b [16]byte) string {
	return fmt.Sprintf("%08x-%04x-%04x-%04x-%012x",
		b[0:4], b[4:6], b[6:8], b[8:10], b[10:16])
}

func formatStringList(ss []string) string {
	parts := make([]string, len(ss))
	for i, s := range ss {
		parts[i] = "'" + escapeSQLString(s) + "'"
	}
	return strings.Join(parts, ", ")
}
