package drain

import (
	"context"
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/x7ssss/dbdrain/internal/anonymize"
	"github.com/x7ssss/dbdrain/internal/config"
	"github.com/x7ssss/dbdrain/internal/graph"
	"github.com/x7ssss/dbdrain/internal/introspect"
)

// Config holds export configuration.
type Config struct {
	Schema          string
	AnonymizePII    bool
	Salt            string
	MaxRowsPerTable int // 0 = unlimited
	MaxDepth        int // 0 = unlimited (downward traversal only)
	Rules           []config.Rule // declarative masking rules from dbdrain.yaml
}

// Row is a single fetched database row: column values in schema order.
type Row struct {
	Table    string
	ColNames []string
	Cols     []introspect.Column
	Vals     []interface{}
}

// polyPair holds a (discriminatorValue, fkValue) pair captured during row emission.
type polyPair struct {
	discVal string // e.g. "post"
	fkVal   string // e.g. "123"
}

// Exporter streams SQL INSERT statements to a writer.
type Exporter struct {
	conn    *pgx.Conn
	schema  *introspect.Schema
	g       *graph.Graph
	sccs    []graph.SCC
	cfg     Config
	masker  *anonymize.Masker
	visited map[string]map[string]bool // table -> set of row PKs

	// polyData: child_table -> discriminatorCol -> []polyPair
	// Populated during fetchAndEmit for tables that have virtual FK edges.
	polyData map[string]map[string][]polyPair

	// RowCounts tracks rows emitted per table (for summary + verify).
	RowCounts map[string]int
}

// New creates a new Exporter.
func New(conn *pgx.Conn, schema *introspect.Schema, g *graph.Graph, sccs []graph.SCC, cfg Config) *Exporter {
	var masker *anonymize.Masker
	if cfg.AnonymizePII {
		masker = anonymize.New(cfg.Salt)
	}
	return &Exporter{
		conn:      conn,
		schema:    schema,
		g:         g,
		sccs:      sccs,
		cfg:       cfg,
		masker:    masker,
		visited:   make(map[string]map[string]bool),
		polyData:  make(map[string]map[string][]polyPair),
		RowCounts: make(map[string]int),
	}
}

// hasCycles returns true if any SCC has a cycle.
func (e *Exporter) hasCycles() bool {
	for _, scc := range e.sccs {
		if scc.HasCycle {
			return true
		}
	}
	return false
}

// -------------------------------------------------------------------------
// SQL emission mode
// -------------------------------------------------------------------------

// Export writes the full SQL dump to w, starting from the anchor table/query.
func (e *Exporter) Export(ctx context.Context, w io.Writer, anchorTable string, anchorWhere string, anchorLimit int) error {
	fmt.Fprintf(w, "-- Generated by dbdrain v0.3.0 on %s\n", time.Now().UTC().Format(time.RFC3339))
	fmt.Fprintf(w, "-- Anchor: %s WHERE %s LIMIT %d\n\n", anchorTable, anchorWhere, anchorLimit)
	fmt.Fprintln(w, "BEGIN;")
	if e.hasCycles() {
		fmt.Fprintln(w, "SET CONSTRAINTS ALL DEFERRED;")
	}
	fmt.Fprintln(w, "")

	tx, err := e.conn.BeginTx(ctx, pgx.TxOptions{IsoLevel: pgx.RepeatableRead, AccessMode: pgx.ReadOnly})
	if err != nil {
		return fmt.Errorf("begin tx: %w", err)
	}
	defer tx.Rollback(ctx)

	if err := e.resolveSelfRef(ctx, tx, w, anchorTable, anchorWhere, anchorLimit); err != nil {
		return fmt.Errorf("resolve self-ref: %w", err)
	}
	if _, err := e.fetchAndEmit(ctx, tx, w, anchorTable, anchorWhere, anchorLimit); err != nil {
		return fmt.Errorf("fetch anchor: %w", err)
	}
	if err := e.bfsParents(ctx, tx, w, anchorTable); err != nil {
		return fmt.Errorf("traverse parents: %w", err)
	}
	if err := e.bfsChildren(ctx, tx, w, anchorTable, 0); err != nil {
		return fmt.Errorf("traverse children: %w", err)
	}

	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "COMMIT;")
	return nil
}

// -------------------------------------------------------------------------
// Direct target streaming mode
// -------------------------------------------------------------------------

// ExportToTarget executes inserts directly against a target pgx.Conn.
func (e *Exporter) ExportToTarget(ctx context.Context, targetConn *pgx.Conn, anchorTable string, anchorWhere string, anchorLimit int, progressFn func(table string, n int)) error {
	tx, err := e.conn.BeginTx(ctx, pgx.TxOptions{IsoLevel: pgx.RepeatableRead, AccessMode: pgx.ReadOnly})
	if err != nil {
		return fmt.Errorf("begin source tx: %w", err)
	}
	defer tx.Rollback(ctx)

	var rows []Row
	if err := e.resolveSelfRefRows(ctx, tx, anchorTable, anchorWhere, anchorLimit, &rows); err != nil {
		return fmt.Errorf("self-ref resolution: %w", err)
	}
	if err := e.collectRows(ctx, tx, anchorTable, anchorWhere, anchorLimit, &rows); err != nil {
		return fmt.Errorf("collect anchor rows: %w", err)
	}
	if err := e.collectParents(ctx, tx, anchorTable, &rows); err != nil {
		return fmt.Errorf("collect parents: %w", err)
	}
	if err := e.collectChildren(ctx, tx, anchorTable, 0, &rows); err != nil {
		return fmt.Errorf("collect children: %w", err)
	}

	targetTx, err := targetConn.Begin(ctx)
	if err != nil {
		return fmt.Errorf("begin target tx: %w", err)
	}
	defer targetTx.Rollback(ctx)

	if _, err := targetTx.Exec(ctx, "SET CONSTRAINTS ALL DEFERRED;"); err != nil {
		return fmt.Errorf("set deferred: %w", err)
	}

	for _, row := range rows {
		if err := e.insertRow(ctx, targetTx, row); err != nil {
			return fmt.Errorf("insert row into %s: %w", row.Table, err)
		}
		if progressFn != nil {
			progressFn(row.Table, 1)
		}
	}

	return targetTx.Commit(ctx)
}

func (e *Exporter) insertRow(ctx context.Context, tx pgx.Tx, row Row) error {
	quoted := make([]string, len(row.ColNames))
	placeholders := make([]string, len(row.ColNames))
	for i, c := range row.ColNames {
		quoted[i] = quoteIdent(c)
		placeholders[i] = fmt.Sprintf("$%d", i+1)
	}
	query := fmt.Sprintf(
		"INSERT INTO %s.%s (%s) VALUES (%s) ON CONFLICT DO NOTHING",
		quoteIdent(e.cfg.Schema),
		quoteIdent(row.Table),
		strings.Join(quoted, ", "),
		strings.Join(placeholders, ", "),
	)
	_, err := tx.Exec(ctx, query, row.Vals...)
	return err
}

// -------------------------------------------------------------------------
// Self-referencing hierarchy resolution
// -------------------------------------------------------------------------

func (e *Exporter) isSelfRef(table string) bool {
	for _, edge := range e.g.OutEdges[table] {
		if edge.ToTable == table {
			return true
		}
	}
	return false
}

func (e *Exporter) selfRefEdge(table string) *graph.Edge {
	for i, edge := range e.g.OutEdges[table] {
		if edge.ToTable == table {
			return &e.g.OutEdges[table][i]
		}
	}
	return nil
}

func (e *Exporter) resolveSelfRef(ctx context.Context, tx pgx.Tx, w io.Writer, table string, anchorWhere string, limit int) error {
	edge := e.selfRefEdge(table)
	if edge == nil || len(edge.FromColumns) != 1 || len(edge.ToColumns) != 1 {
		return nil
	}
	childCol, parentCol := edge.FromColumns[0], edge.ToColumns[0]
	cols := e.schema.Columns[table]
	if len(cols) == 0 {
		return nil
	}
	colNames := colNameSlice(cols)
	selectCols := "t." + strings.Join(colNames, ", t.")
	seedWhere, seedLimit := buildSeedClauses(anchorWhere, limit)

	cteSQL := fmt.Sprintf(`
WITH RECURSIVE hierarchy AS (
  SELECT %s FROM %s.%s t %s %s
  UNION
  SELECT %s FROM %s.%s t INNER JOIN hierarchy h ON t.%s = h.%s
  UNION
  SELECT %s FROM %s.%s t INNER JOIN hierarchy h ON t.%s = h.%s
)
SELECT DISTINCT * FROM hierarchy`,
		selectCols, quoteIdent(e.cfg.Schema), quoteIdent(table), seedWhere, seedLimit,
		selectCols, quoteIdent(e.cfg.Schema), quoteIdent(table), quoteIdent(parentCol), quoteIdent(childCol),
		selectCols, quoteIdent(e.cfg.Schema), quoteIdent(table), quoteIdent(childCol), quoteIdent(parentCol),
	)

	rows, err := tx.Query(ctx, cteSQL)
	if err != nil {
		return fmt.Errorf("recursive CTE for %s: %w", table, err)
	}
	defer rows.Close()

	pkCols := e.schema.PrimaryKeys[table]
	for rows.Next() {
		vals, err := rows.Values()
		if err != nil {
			return err
		}
		pk := buildPK(pkCols, colNames, vals)
		if e.markVisited(table, pk) {
			continue
		}
		e.applyMasking(table, cols, vals)
		e.capturePolyData(table, colNames, vals)
		fmt.Fprintf(w, "INSERT INTO %s.%s (%s) VALUES (%s) ON CONFLICT DO NOTHING;\n",
			quoteIdent(e.cfg.Schema), quoteIdent(table),
			strings.Join(quotedColNames(colNames), ", "),
			formatValues(cols, vals),
		)
		e.RowCounts[table]++
	}
	return rows.Err()
}

func (e *Exporter) resolveSelfRefRows(ctx context.Context, tx pgx.Tx, table string, anchorWhere string, limit int, out *[]Row) error {
	edge := e.selfRefEdge(table)
	if edge == nil || len(edge.FromColumns) != 1 || len(edge.ToColumns) != 1 {
		return nil
	}
	childCol, parentCol := edge.FromColumns[0], edge.ToColumns[0]
	cols := e.schema.Columns[table]
	if len(cols) == 0 {
		return nil
	}
	colNames := colNameSlice(cols)
	selectCols := "t." + strings.Join(colNames, ", t.")
	seedWhere, seedLimit := buildSeedClauses(anchorWhere, limit)

	cteSQL := fmt.Sprintf(`
WITH RECURSIVE hierarchy AS (
  SELECT %s FROM %s.%s t %s %s
  UNION
  SELECT %s FROM %s.%s t INNER JOIN hierarchy h ON t.%s = h.%s
  UNION
  SELECT %s FROM %s.%s t INNER JOIN hierarchy h ON t.%s = h.%s
)
SELECT DISTINCT * FROM hierarchy`,
		selectCols, quoteIdent(e.cfg.Schema), quoteIdent(table), seedWhere, seedLimit,
		selectCols, quoteIdent(e.cfg.Schema), quoteIdent(table), quoteIdent(parentCol), quoteIdent(childCol),
		selectCols, quoteIdent(e.cfg.Schema), quoteIdent(table), quoteIdent(childCol), quoteIdent(parentCol),
	)

	rows, err := tx.Query(ctx, cteSQL)
	if err != nil {
		return fmt.Errorf("recursive CTE for %s: %w", table, err)
	}
	defer rows.Close()

	pkCols := e.schema.PrimaryKeys[table]
	for rows.Next() {
		vals, err := rows.Values()
		if err != nil {
			return err
		}
		pk := buildPK(pkCols, colNames, vals)
		if e.markVisited(table, pk) {
			continue
		}
		e.applyMasking(table, cols, vals)
		e.capturePolyData(table, colNames, vals)
		*out = append(*out, Row{Table: table, ColNames: colNames, Cols: cols, Vals: vals})
		e.RowCounts[table]++
	}
	return rows.Err()
}

// -------------------------------------------------------------------------
// BFS traversal — SQL emission path
// -------------------------------------------------------------------------

func (e *Exporter) bfsParents(ctx context.Context, tx pgx.Tx, w io.Writer, startTable string) error {
	queue := []string{startTable}
	enqueued := map[string]bool{startTable: true}

	for len(queue) > 0 {
		table := queue[0]
		queue = queue[1:]

		// Regular FK parents.
		for _, edge := range e.g.OutEdges[table] {
			parent := edge.ToTable
			if parent == table || len(edge.ToColumns) != 1 {
				continue
			}
			fkVals := e.visitedPKs(table)
			if len(fkVals) == 0 {
				continue
			}
			where := fmt.Sprintf("%s IN (%s)", quoteIdent(edge.ToColumns[0]), formatStringList(fkVals))
			if _, err := e.fetchAndEmit(ctx, tx, w, parent, where, 0); err != nil {
				return err
			}
			if !enqueued[parent] {
				enqueued[parent] = true
				queue = append(queue, parent)
			}
		}

		// Virtual FK (polymorphic) parents.
		if err := e.resolveVirtualParents(ctx, tx, w, table, &queue, enqueued); err != nil {
			return err
		}
	}
	return nil
}

func (e *Exporter) bfsChildren(ctx context.Context, tx pgx.Tx, w io.Writer, startTable string, _ int) error {
	type work struct {
		table string
		depth int
	}
	queue := []work{{startTable, 0}}
	enqueued := map[string]bool{startTable: true}

	for len(queue) > 0 {
		item := queue[0]
		queue = queue[1:]

		if e.cfg.MaxDepth > 0 && item.depth >= e.cfg.MaxDepth {
			continue
		}

		for _, edge := range e.g.InEdges[item.table] {
			child := edge.FromTable
			if child == item.table || len(edge.FromColumns) != 1 {
				continue
			}
			fkVals := e.visitedPKs(item.table)
			if len(fkVals) == 0 {
				continue
			}
			where := fmt.Sprintf("%s IN (%s)", quoteIdent(edge.FromColumns[0]), formatStringList(fkVals))
			if _, err := e.fetchAndEmit(ctx, tx, w, child, where, e.cfg.MaxRowsPerTable); err != nil {
				return err
			}
			if !enqueued[child] {
				enqueued[child] = true
				queue = append(queue, work{child, item.depth + 1})
			}
		}
	}
	return nil
}

// resolveVirtualParents resolves polymorphic parents for `table` using captured polyData.
func (e *Exporter) resolveVirtualParents(ctx context.Context, tx pgx.Tx, w io.Writer, table string, queue *[]string, enqueued map[string]bool) error {
	for _, ve := range e.g.VirtualEdges[table] {
		discGroups := e.polyData[table][ve.DiscriminatorCol]
		// Group fk values by discriminator value.
		grouped := map[string][]string{} // discVal -> []fkVal
		for _, pp := range discGroups {
			grouped[pp.discVal] = append(grouped[pp.discVal], pp.fkVal)
		}
		for discVal, fkVals := range grouped {
			tc, ok := ve.Mappings[discVal]
			if !ok {
				continue // unknown discriminator value in this slice
			}
			where := fmt.Sprintf("%s IN (%s)", quoteIdent(tc.Column), formatStringList(fkVals))
			if _, err := e.fetchAndEmit(ctx, tx, w, tc.Table, where, 0); err != nil {
				return fmt.Errorf("virtual FK parent fetch (%s→%s): %w", table, tc.Table, err)
			}
			if !enqueued[tc.Table] {
				enqueued[tc.Table] = true
				*queue = append(*queue, tc.Table)
			}
		}
	}
	return nil
}

// -------------------------------------------------------------------------
// BFS traversal — target streaming path
// -------------------------------------------------------------------------

func (e *Exporter) collectParents(ctx context.Context, tx pgx.Tx, startTable string, out *[]Row) error {
	queue := []string{startTable}
	enqueued := map[string]bool{startTable: true}

	for len(queue) > 0 {
		table := queue[0]
		queue = queue[1:]

		for _, edge := range e.g.OutEdges[table] {
			parent := edge.ToTable
			if parent == table || len(edge.ToColumns) != 1 {
				continue
			}
			fkVals := e.visitedPKs(table)
			if len(fkVals) == 0 {
				continue
			}
			where := fmt.Sprintf("%s IN (%s)", quoteIdent(edge.ToColumns[0]), formatStringList(fkVals))
			if err := e.collectRows(ctx, tx, parent, where, 0, out); err != nil {
				return err
			}
			if !enqueued[parent] {
				enqueued[parent] = true
				queue = append(queue, parent)
			}
		}

		// Virtual FK polymorphic parents.
		if err := e.collectVirtualParentRows(ctx, tx, table, out, &queue, enqueued); err != nil {
			return err
		}
	}
	return nil
}

func (e *Exporter) collectChildren(ctx context.Context, tx pgx.Tx, startTable string, _ int, out *[]Row) error {
	type work struct {
		table string
		depth int
	}
	queue := []work{{startTable, 0}}
	enqueued := map[string]bool{startTable: true}

	for len(queue) > 0 {
		item := queue[0]
		queue = queue[1:]
		if e.cfg.MaxDepth > 0 && item.depth >= e.cfg.MaxDepth {
			continue
		}
		for _, edge := range e.g.InEdges[item.table] {
			child := edge.FromTable
			if child == item.table || len(edge.FromColumns) != 1 {
				continue
			}
			fkVals := e.visitedPKs(item.table)
			if len(fkVals) == 0 {
				continue
			}
			where := fmt.Sprintf("%s IN (%s)", quoteIdent(edge.FromColumns[0]), formatStringList(fkVals))
			if err := e.collectRows(ctx, tx, child, where, e.cfg.MaxRowsPerTable, out); err != nil {
				return err
			}
			if !enqueued[child] {
				enqueued[child] = true
				queue = append(queue, work{child, item.depth + 1})
			}
		}
	}
	return nil
}

func (e *Exporter) collectVirtualParentRows(ctx context.Context, tx pgx.Tx, table string, out *[]Row, queue *[]string, enqueued map[string]bool) error {
	for _, ve := range e.g.VirtualEdges[table] {
		grouped := map[string][]string{}
		for _, pp := range e.polyData[table][ve.DiscriminatorCol] {
			grouped[pp.discVal] = append(grouped[pp.discVal], pp.fkVal)
		}
		for discVal, fkVals := range grouped {
			tc, ok := ve.Mappings[discVal]
			if !ok {
				continue
			}
			where := fmt.Sprintf("%s IN (%s)", quoteIdent(tc.Column), formatStringList(fkVals))
			if err := e.collectRows(ctx, tx, tc.Table, where, 0, out); err != nil {
				return err
			}
			if !enqueued[tc.Table] {
				enqueued[tc.Table] = true
				*queue = append(*queue, tc.Table)
			}
		}
	}
	return nil
}

// -------------------------------------------------------------------------
// Core fetch helpers
// -------------------------------------------------------------------------

func (e *Exporter) markVisited(table string, pk string) bool {
	if _, ok := e.visited[table]; !ok {
		e.visited[table] = make(map[string]bool)
	}
	if e.visited[table][pk] {
		return true
	}
	e.visited[table][pk] = true
	return false
}

func (e *Exporter) visitedPKs(table string) []string {
	pks := make([]string, 0, len(e.visited[table]))
	for pk := range e.visited[table] {
		pks = append(pks, pk)
	}
	return pks
}

// capturePolyData records discriminator+fk value pairs for tables with virtual edges.
func (e *Exporter) capturePolyData(table string, colNames []string, vals []interface{}) {
	virtualEdges, ok := e.g.VirtualEdges[table]
	if !ok || len(virtualEdges) == 0 {
		return
	}
	// Build a column-index lookup once.
	colIdx := make(map[string]int, len(colNames))
	for i, c := range colNames {
		colIdx[c] = i
	}

	for _, ve := range virtualEdges {
		discIdx, hasDisc := colIdx[ve.DiscriminatorCol]
		fkIdx, hasFK := colIdx[ve.ChildColumn]
		if !hasDisc || !hasFK {
			continue
		}
		discVal := fmt.Sprintf("%v", vals[discIdx])
		fkVal := fmt.Sprintf("%v", vals[fkIdx])
		if discVal == "<nil>" || fkVal == "<nil>" {
			continue
		}

		if e.polyData[table] == nil {
			e.polyData[table] = make(map[string][]polyPair)
		}
		e.polyData[table][ve.DiscriminatorCol] = append(
			e.polyData[table][ve.DiscriminatorCol],
			polyPair{discVal: discVal, fkVal: fkVal},
		)
	}
}

func (e *Exporter) fetchAndEmit(ctx context.Context, tx pgx.Tx, w io.Writer, table string, whereClause string, limit int) ([]string, error) {
	cols := e.schema.Columns[table]
	if len(cols) == 0 {
		return nil, nil
	}
	colNames := colNameSlice(cols)
	query := buildQuery(e.cfg.Schema, table, colNames, whereClause, limit)

	rows, err := tx.Query(ctx, query)
	if err != nil {
		return nil, fmt.Errorf("query %s: %w", table, err)
	}
	defer rows.Close()

	pkCols := e.schema.PrimaryKeys[table]
	var pks []string

	for rows.Next() {
		vals, err := rows.Values()
		if err != nil {
			return nil, fmt.Errorf("row values %s: %w", table, err)
		}
		pk := buildPK(pkCols, colNames, vals)
		if e.markVisited(table, pk) {
			continue
		}
		pks = append(pks, pk)
		e.applyMasking(table, cols, vals)
		e.capturePolyData(table, colNames, vals)
		fmt.Fprintf(w, "INSERT INTO %s.%s (%s) VALUES (%s) ON CONFLICT DO NOTHING;\n",
			quoteIdent(e.cfg.Schema), quoteIdent(table),
			strings.Join(quotedColNames(colNames), ", "),
			formatValues(cols, vals),
		)
		e.RowCounts[table]++
	}
	return pks, rows.Err()
}

func (e *Exporter) collectRows(ctx context.Context, tx pgx.Tx, table string, whereClause string, limit int, out *[]Row) error {
	cols := e.schema.Columns[table]
	if len(cols) == 0 {
		return nil
	}
	colNames := colNameSlice(cols)
	query := buildQuery(e.cfg.Schema, table, colNames, whereClause, limit)

	rows, err := tx.Query(ctx, query)
	if err != nil {
		return fmt.Errorf("query %s: %w", table, err)
	}
	defer rows.Close()

	pkCols := e.schema.PrimaryKeys[table]
	for rows.Next() {
		vals, err := rows.Values()
		if err != nil {
			return fmt.Errorf("row values %s: %w", table, err)
		}
		pk := buildPK(pkCols, colNames, vals)
		if e.markVisited(table, pk) {
			continue
		}
		e.applyMasking(table, cols, vals)
		e.capturePolyData(table, colNames, vals)
		*out = append(*out, Row{Table: table, ColNames: colNames, Cols: cols, Vals: vals})
		e.RowCounts[table]++
	}
	return rows.Err()
}

// -------------------------------------------------------------------------
// Masking
// -------------------------------------------------------------------------

// applyMasking applies config rules first, falling back to auto-heuristics.
func (e *Exporter) applyMasking(table string, cols []introspect.Column, vals []interface{}) {
	if e.masker == nil {
		return
	}
	// Build a temporary config view for rule lookups.
	ruleset := config.Config{Rules: e.cfg.Rules}

	for i, col := range cols {
		if vals[i] == nil {
			continue
		}
		strVal := fmt.Sprintf("%v", vals[i])

		if rule := ruleset.FindRule(table, col.Name); rule != nil {
			masked := e.masker.ApplyTransform(string(rule.Transform), col.Name, strVal)
			if masked != strVal {
				vals[i] = masked
			}
		} else {
			masked := e.masker.MaskColumn(col.Name, strVal)
			if masked != strVal {
				vals[i] = masked
			}
		}
	}
}

// -------------------------------------------------------------------------
// Helpers
// -------------------------------------------------------------------------

func buildSeedClauses(where string, limit int) (string, string) {
	w, l := "", ""
	if where != "" {
		w = "WHERE " + where
	}
	if limit > 0 {
		l = fmt.Sprintf("LIMIT %d", limit)
	}
	return w, l
}

func colNameSlice(cols []introspect.Column) []string {
	names := make([]string, len(cols))
	for i, c := range cols {
		names[i] = c.Name
	}
	return names
}

func buildQuery(schema, table string, colNames []string, whereClause string, limit int) string {
	q := fmt.Sprintf(`SELECT %s FROM %s.%s`,
		quoteIdents(colNames),
		quoteIdent(schema),
		quoteIdent(table),
	)
	if whereClause != "" {
		q += " WHERE " + whereClause
	}
	if limit > 0 {
		q += fmt.Sprintf(" LIMIT %d", limit)
	}
	return q
}

func quoteIdent(s string) string {
	return `"` + strings.ReplaceAll(s, `"`, `""`) + `"`
}

func quoteIdents(ss []string) string {
	parts := make([]string, len(ss))
	for i, s := range ss {
		parts[i] = quoteIdent(s)
	}
	return strings.Join(parts, ", ")
}

func quotedColNames(names []string) []string {
	out := make([]string, len(names))
	for i, n := range names {
		out[i] = quoteIdent(n)
	}
	return out
}

func buildPK(pkCols []string, colNames []string, vals []interface{}) string {
	if len(pkCols) == 0 {
		return fmt.Sprintf("%v", vals)
	}
	parts := make([]string, 0, len(pkCols))
	for _, pk := range pkCols {
		for j, col := range colNames {
			if col == pk {
				parts = append(parts, fmt.Sprintf("%v", vals[j]))
				break
			}
		}
	}
	return strings.Join(parts, ",")
}

func formatValues(cols []introspect.Column, vals []interface{}) string {
	parts := make([]string, len(vals))
	for i, v := range vals {
		parts[i] = formatValue(cols[i], v)
	}
	return strings.Join(parts, ", ")
}

func formatValue(col introspect.Column, v interface{}) string {
	if v == nil {
		return "NULL"
	}
	switch val := v.(type) {
	case bool:
		if val {
			return "TRUE"
		}
		return "FALSE"
	case int, int8, int16, int32, int64,
		uint, uint8, uint16, uint32, uint64,
		float32, float64:
		return fmt.Sprintf("%v", val)
	case []byte:
		dt := strings.ToLower(col.DataType)
		if strings.Contains(dt, "json") {
			return "'" + escapeSQLString(string(val)) + "'"
		}
		return fmt.Sprintf("'\\x%s'", fmt.Sprintf("%x", val))
	case time.Time:
		return fmt.Sprintf("'%s'", val.UTC().Format(time.RFC3339Nano))
	case [16]byte:
		return fmt.Sprintf("'%s'", formatUUID(val))
	default:
		return "'" + escapeSQLString(fmt.Sprintf("%v", val)) + "'"
	}
}

func escapeSQLString(s string) string {
	return strings.ReplaceAll(s, "'", "''")
}

func formatUUID(b [16]byte) string {
	return fmt.Sprintf("%08x-%04x-%04x-%04x-%012x",
		b[0:4], b[4:6], b[6:8], b[8:10], b[10:16])
}

func formatStringList(ss []string) string {
	parts := make([]string, len(ss))
	for i, s := range ss {
		parts[i] = "'" + escapeSQLString(s) + "'"
	}
	return strings.Join(parts, ", ")
}
